### ISSUE TITLE
Panning mode doesn't exist in 3.01

### ISSUE THREAD

**Issue by Magnatauren** [simbrain/simbrain#33]
There doesn't seem to be a panning mode in 3.01 anymore. In addition to this the Ctrl+drag also doesn't work to pan. It just creates a lasso. It worked in 3-Beta and that was the last release I used.

**Comment by jyoshimi** [comment]
Hi there.    Panning mode was removed because of ctrl-drag.   It only works in when auto-zoom is turned off, which is now more conveniently accessible in the toolbar (the zoom icon with an "A" in it; it's a button ).  When you click that are you able to ctrl-drag (or on mac cmd-drag)?  I have confirmed all this works on my machine.

**Comment by idonai** [comment]
hello there, i cant get it to work either. when holding "ctrl" i cant press on screen and drag it around. it only makes the yellow selection box....

**Comment by jyoshimi** [comment]
What kind of machine are you using idonai?

**Comment by idonai** [comment]
Asus V3-772G

**Comment by jyoshimi** [comment]
Ok guys, you were right.    Ctrl was not working on PC.   We changed it to shift-click, and tested it on PC.    This will be released with 3.02.

**Comment by jyoshimi** [comment]
3.02 Released
