### ISSUE TITLE
slope change when editing neuron

### ISSUE THREAD

**Issue by idonai** [simbrain/simbrain#34]
Hello, i dont know if this is a bug that has been reported, but
1)I create a neuron, right click it and press "edit 1 selected neuron"(or more neurons) 
2) I change nothing but press the "ok" button. The slope automatically changes.(when i reopen the edit screen the slope is multiplied with 10).

**Comment by idonai** [comment]
I found the real issue the program doesnt recognize the . (dot) when typing 1.0 and makes it into 10
if you change 1.0 to 1.00 the program thinks its 100.
might there be a programming error recarding the use of dots and comma's? 
The program does recognize 1,0 as 1 but changes it to 1.0 in the edit screen so that the next time you press "ok" on the edit screen it becomes 10 anyway :/

**Comment by zachtosi** [comment]
Well that's an annoying error. Are you in a region that uses commas instead of periods to denote decimals? If that's the case, it looks like a parser in one part of the program is paying attention to regional markers while another isn't and they're conflicting... I will look into this.

**Comment by idonai** [comment]
Yes i live in the netherlands (europe)

**Comment by zachtosi** [comment]
Alright, I believe I've fixed the problem. See: eb71f6cefc959dbcd607f01fa6f7427d7c4fcbd6 . I've tested it on my machine manually setting the locale to Germany. Let me know if it resolves the issue for you.

However I've discovered that the problem is endemic to pretty much all the other panels... thank you for bringing our unintentional American-centric programming to light! The synapse panels have not been updated to use the neuron panel API so when we update that we will fix the bug there. I will begin addressing the bug in the special neuron group and subnetwork panels as well.

**Comment by idonai** [comment]
Okay thanks :)

**Comment by idonai** [comment]
Will test if it works(might take a few days)

**Comment by jyoshimi** [comment]
Thanks for noting this idonai and thanks for your work fixing it Zah!  Someone else raised the issue previously and I could not replicate.  Zach were you able to replicate the problem on a US machine by setting localle to Germany?  I know you say you tested the fix, but were you able to see the problem?

**Comment by zachtosi** [comment]
Yes I was able to replicate the problem by changing the default locale to one which uses different decimal formatting (in this case Germany made a good test since they use commas to denote decimals rather than grouping). If you've yet to sync try putting:

Locale.setDefault(Locale.GERMANY);

In a static initializer block anywhere in the program and you will be able to see the problem.

**Comment by idonai** [comment]
sorry for the lame question but how can i test if it works whit my machine? i cant really code and dont realy know where to put the src. (i suppose in the jar but where?) Is there a walkthrough on this site?

**Comment by jyoshimi** [comment]
Not lame at all!  This stuff is non-obvious.    There is some information here: https://github.com/simbrain/simbrain/wiki/Running-from-source

If that doesn't work I can post a quick test build tomorrow. Cheers.

**Comment by idonai** [comment]
How easy is it for you to post a test build?

**Comment by jyoshimi** [comment]
It's not so hard.   I  know I said today but unless you need it sooner, I'll post it later in the week (maybe Thursday night), since we have a few more things to fix  anyway.

**Comment by idonai** [comment]
No hurry, thank you for wanting to make a test build

**Comment by jyoshimi** [comment]
Ok try this

**Comment by idonai** [comment]
The slope is working correctly and stays the same.
The "ceiling" under the noise tap does still change, but this doesn't matter for me though :)
Thanks for fixing *Thumbs Up*

**Comment by jyoshimi** [comment]
Thanks again for noting this.  We now know what the issue is and have a way to fix it.   Time permitting we'll change as much as possible before 3.02 is released.

**Comment by gitfortat** [comment]
I am from Germany and had the same problem with the decimal separator. This problem also happens with the emergent simulation software (even more american-centric progamming :)), where it suffices to change the locale to US. Unfortunately this does not work for simbrain, at least not under Windows. But for a quick workaround you could just use GNU/linux and set the locale to US. I am wondering why changing the decimal separator in Windows does not have any effect on simbrain. Happy to see that a fix is on its way. Keep up the great work!

**Comment by jyoshimi** [comment]
See #35, #37
